### ISSUE TITLE
Broken progress bar on v5.0.0

### ISSUE THREAD

**Issue by senhan07** [Carve/qbittorrent-webui-cjratliff.com#80]
![image](https://github.com/user-attachments/assets/650268c1-e305-46ee-8074-64ca6fc19ef4)

**Comment by mdeeter** [comment]
I updated my local `cjratliff.css` to use:

```css
--darkmode-primary: #3ca4d4;
--darkmode-progress-bg: #aaa;
```

and 

```css
.progressbar_light{
	background: var(--darkmode-progress-bg) !important;
}
```

![image](https://github.com/user-attachments/assets/46d96bc0-cd86-4376-ad44-34a56f52d69c)
